name: Go
on:
  push:
    branches:
      - master

jobs:

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Reattach HEAD
      run: git checkout 
      
    - name: release
      env:
        # I couldn't get the releases to work with the GITHUB_TOKEN so made secrets... :(
        GH_DEPLOY_USER: ${{ secrets.GH_DEPLOY_USER }}
        GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
      run: |
        branch2="$(echo \"$GITHUB_REF\" | awk -F / '{ print $3 })"
        echo "Branch2: $BRANCH2"
        git config --global user.email "ci@gochain.io"
        git config --global user.name "CI"
        git branch --set-upstream-to=origin/$branch2 $branch2
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        ./release.sh        
  build-mac:
    name: Build MacOS
    runs-on: macOS-latest
    needs: build-linux
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -o web3_mac ./cmd/web3
      
    - name: release
      env:
        # I couldn't get the releases to work with the GITHUB_TOKEN so made secrets... :(
        GH_DEPLOY_USER: ${{ secrets.GH_DEPLOY_USER }}
        GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
      run: |
        version=$(git describe --match "v[0-9]*" --abbrev=0 HEAD)
        url='https://api.github.com/repos/gochain/web3/releases'
        output=$(curl -s -u $GH_DEPLOY_USER:$GH_DEPLOY_KEY -d "{\"tag_name\": \"v$version\", \"name\": \"v$version\"}" $url)
        echo "output: $output"
        upload_url=$(echo "$output" | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["upload_url"]' | sed -E "s/\{.*//")
        html_url=$(echo "$output" | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["html_url"]')
        curl --data-binary "@web3_mac"  -H "Content-Type: application/octet-stream" -u $GH_DEPLOY_USER:$GH_DEPLOY_KEY $upload_url\?name\=web3_mac >/dev/null
        
